name: "templ Generator Action"
description: "An action that generates Go code from templ files"
inputs:
  directory:
    description: "The directory where to look for .templ files."
    required: false
    default: "."
  commit-message:
    description: "Custom commit message for the generated code."
    required: false
    default: "chore: generate go code from templ files"
  commit:
    description: "Flag to enable or disable committing changes."
    required: false
    default: "true"
  create-pull-request:
    description: "Whether to create a pull request instead of committing directly."
    required: false
    default: "false"
  pull-request-target-branch:
    description: "The target branch for the pull request."
    required: false
    default: "main" # or 'master' depending on the default branch
  pull-request-branch-name:
    description: "The branch name for the commits with the generated code."
    required: false
    default: "templ/update-generated-code"
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: "stable"
    - run: |
        go install github.com/a-h/templ/cmd/templ@latest \
        templ fmt -path ${{ inputs.directory }} \
        templ generate -path ${{ inputs.directory }} \
